# Generated by Django 5.2.9 on 2026-01-06 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Jeune',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('genre', models.CharField(max_length=10)),
                ('zone', models.CharField(max_length=100)),
                ('adresse', models.TextField()),
                ('telephone', models.CharField(max_length=15)),
                ('telephone2', models.CharField(blank=True, max_length=15, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('Domaine_activite', models.CharField(blank=True, max_length=100, null=True)),
                ('Niveau_etude', models.CharField(blank=True, max_length=100, null=True)),
                ('competences', models.TextField()),
                ('numero_cni', models.CharField(max_length=50, unique=True)),
                ('matricule', models.CharField(blank=True, max_length=50, null=True, unique=True)),
            ],
        ),
    ]
